### PR TITLE
Fix/114 fix data soure filter

### LINKED ISSUE #114: Fix data source filter
Figma PL Style: https://www.figma.com/design/xTTrqo17a8ORVXYQFLXeeD/%F0%9F%87%B5%F0%9F%87%B1-Search---Polski-EOSC?node-id=9762-17754&t=wdoR8AJZA73wNG7l-1

Figma example: https://www.figma.com/design/mGO12IHXsIuWQUUHSJ5oZT/Navigation?node-id=9457-2256&t=RAlBCWg6qAkUDnEc-1

Scope:

Image

- [ ] NOTE: its relevant for all collections that have data source filter 
- [ ] this filter should have the same font size like other filters
- [ ] it should be placed belove EOSC Node filter (second filter on the left)

- [ ] delete:
Image

### PR DESCRIPTION
**Pull request by sqrasdf**
closes #114

### CODE REVIEW

File: ui/apps/ui/src/app/components/page-header/page-header.component.ts [hunk 1]
```diff
@@ -19,26 +19,26 @@ import { DEFAULT_SCOPE } from '@collections/services/custom-route.service';
...
-            [filterId]="filterConfig.id"
-            [data]="filterConfig.options"
-            [isLoading]="!!(isLoading$ | async)"
-            [show]="resultsCount > 0 && filterConfig.options.length > 0"
-            [tooltipText]="filterConfig.tooltipText"
-          ></ess-filter-multiselect-dropdown>
-        </ng-container>
-      </ng-container>
-    </div>
+    <!--    <div-->
```
Comment (Michal-Kolomanski) [inline ui/apps/ui/src/app/components/page-header/page-header.component.ts]: we can delete that

**Review by Michal-Kolomanski — APPROVED** [review]
Impressive work! 💪 

Not sure why we are excluding "eosc" value in the Community Catalogue filter @agpul @AlicjaSwierad 
Currently, that is the only value - if we exclude that - filter becomes empty
https://github.com/cyfronet-fid/pl-discovery-hub/blob/ee5b2e8799f382c9f0aad640ff171c5a1bf95025/ui/apps/ui/src/app/collections/data/utils.ts#L153
